schema_version: 1

context:
  version: "1.0.7"

package:
  name: eventcv
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/eventcv/eventcv-${{ version }}.tar.gz
  sha256: d91f681ff776bab9eff86cd738747ac7f568e23c0a9ad3c7ed2440f73a81b502

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output ${{ SRC_DIR }}/THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.8,<2
  host:
    - python
    - pip
    - maturin >=1.8,<2
    - cmake >=3.18
  run:
    - python
    - numpy >=1.24

tests:
  - python:
      imports:
        - eventcv
      pip_check: true

about:
  summary: Open source event-based computer vision library.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/eventcv/

extra:
  recipe-maintainers:
    - AdamDHines
