schema_version: 1

context:
  version: "1.0.0"

package:
  name: eventcv
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/eventcv/eventcv-${{ version }}.tar.gz
  sha256: 0936650a5b74a3be0cad4de85a7c223fd047ae208f86a5ae7f535e542e693a5e

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output ${{ SRC_DIR }}/THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - python
    - pip
    - maturin >=1.8,<2
    - cmake >=3.18
  run:
    - python
    - numpy >=1.24,<2

tests:
  - python:
      imports:
        - eventcv
      pip_check: true

about:
  summary: Open source event-based computer vision library.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/eventcv/

extra:
  recipe-maintainers:
    - AdamDHines
