schema_version: 1

context:
  version: "1.0.0"

package:
  name: eventcv
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/eventcv/eventcv-${{ version }}.tar.gz
  sha256: 0936650a5b74a3be0cad4de85a7c223fd047ae208f86a5ae7f535e542e693a5e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - eventcv
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Open source event-based computer vision library.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/eventcv/

extra:
  recipe-maintainers:
    - AdamDHines
